# Lab Exercise

In [2]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [9]:
data = pd.read_csv("jester-data-1.csv")

d = data.to_latex()
text_file = open("Output.txt", "w")
text_file.write(d)
text_file.close()

#data

In [6]:
data.describe()

,74,-7.82,8.79,-9.66,-8.16,-7.52,-8.5,-9.85,4.17,-8.98,...,2.82.2,99.18,99.19,99.20,99.21,99.22,-5.63,99.23,99.24,99.25
count,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000,...,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000,24982.000000
mean,72.467417,34.403125,27.094822,33.265435,36.246713,0.427554,19.343233,-0.401425,-0.616301,36.230231,...,61.464367,60.278340,60.420157,59.058023,58.748286,58.539484,58.019793,57.059971,55.751626,60.136534
std,21.860035,46.707230,44.228739,46.747682,48.813136,5.472535,37.861118,5.741420,5.008903,48.228481,...,47.334898,47.946774,47.360166,48.196506,48.311024,48.130845,48.163962,48.717708,49.237364,47.913859
min,36.000000,-9.950000,-9.950000,-9.950000,-9.950000,-9.950000,-9.950000,-9.950000,-9.950000,-9.950000,...,-9.950000,-9.950000,-9.950000,-9.950000,-9.950000,-9.950000,-9.950000,-9.950000,-9.950000,-9.950000
25%,53.000000,-0.150000,-2.180000,-1.120000,-3.350000,-3.690000,-0.390000,-5.290000,-4.610000,-1.750000,...,4.760000,3.590000,4.610000,3.250000,3.160000,3.300000,3.590000,2.670000,1.322500,3.930000
50%,72.000000,5.050000,3.690000,4.660000,3.450000,1.120000,3.540000,-0.050000,-0.290000,4.030000,...,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000
75%,100.000000,99.000000,99.000000,99.000000,99.000000,4.470000,8.010000,3.930000,3.060000,99.000000,...,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000
max,100.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,...,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000